---
- name: Deploy to EKS
  hosts: k8s
  gather_facts: no
  tasks:
    - name: Copy Kubernetes manifests
      copy:
        src: "{{ item }}"
        dest: /home/ec2-user/deploy/{{ item }}
      loop:
        - souq-svc.yml
        - souq-deploy.yaml

    - name: Apply Kubernetes manifests
      shell: |
        kubectl apply -f /home/ec2-user/deploy/{{ item }}
      loop:
        - souq-deploy.yaml
        - souq-svc.yml
