apiVersion: v1
kind: Namespace
metadata:
  name: souq-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: souqmuscat-backend
  namespace: souq-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: souqmuscat-backend
  template:
    metadata:
      labels:
        app: souqmuscat-backend
    spec:
      containers:
      - name: souqmuscat-backend
        image: public.ecr.aws/h0r7c1y8/souqmuscatnode:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
