apiVersion: v1
kind: Service
metadata:
  name: souqmuscat-backend
  namespace: souq-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: souqmuscat-backend
